name: Fetch and Update Menu

on:
  schedule:
    - cron: '30 19 * * *'  # Run daily at 7:30 PM UTC (1:00 AM IST)
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch menu data and save to file
      run: |
        python -c "
        import requests
        import json
        
        url = 'https://api.ssms-pilani.in/menu-next-seven-days'
        response = requests.get(url, verify=False)
        
        with open('urls.json', 'w') as f:
            json.dump(response.json(), f, indent=2)
        "

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add urls.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update menu data" && git push)
