name: Fetch and Update Menu

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 12:30 PM IST (7:00 AM UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch menu data and save to file
        run: |
          python -c "
          import requests
          import json

          url = 'https://api.ssms-pilani.in/menu-next-seven-days'
          response = requests.get(url, verify=False)

          with open('urls.json', 'w') as f:
              json.dump(response.json(), f, indent=2)
          "

      - name: Check if there are changes and commit with date and time
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add urls.json
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            DATE_TIME=$(date +"%Y-%m-%d %H:%M:%S")
            git commit -m "Update menu data - $DATE_TIME"
            git push
          fi
        shell: bash
